version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - my-network
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my-network

  python-script:
    build:
      context: ./database
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - my-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:      
      - backend

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data: